---
- name: Ensure Outpost Directory Exists
  ansible.builtin.file:
    path: /opt/outpost/bin
    state: directory
    mode: '0755'
  become: true
  
- name: Copy Outpost Server Binary
  ansible.builtin.copy:
    src: outpost_server_pizero
    dest: /opt/outpost/bin/outpost_server
    mode: '0700'
  become: true

- name: Copy hostapd Config
  ansible.builtin.copy:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Copy dnsmasq Config
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Copy Outpost Service File
  ansible.builtin.copy:
    src: outpost.service
    dest: /etc/systemd/system/outpost.service
    owner: root
    group: root
    mode: '0644'
  become: true