---
- name: Install necessary dependencies
  ansible.builtin.import_tasks: apt.yml

- name: Copy necessary files
  ansible.builtin.import_tasks: files.yml

- name: Start systemd services
  ansible.builtin.import_tasks: systemd.yml

- name: Install RaspAP
  ansible.builtin.import_tasks: raspap.yml
