---
- name: Install necessary dependencies
  ansible.builtin.import_tasks: install_deps.yml

- name: Copy necessary files
  ansible.builtin.import_tasks: copy_files.yml

- name: Configure networking
  ansible.builtin.import_tasks: net_config.yml

- name: Start systemd services
  ansible.builtin.import_tasks: systemd.yml
