---
- name: Install necessary dependencies
  ansible.builtin.import_tasks: install_deps.yml

- name: Copy necessary files
  ansible.builtin.import_tasks: copy_files.yml

- name: Flush handlers before managing services
  ansible.builtin.meta: flush_handlers

- name: Start systemd services
  ansible.builtin.import_tasks: systemd.yml
