---
- name: Reload systemd cache
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart hostapd
  ansible.buildin.systemd_service:
    name: hostapd
    state: restarted
    enabled: true
  become: true

- name: Restart dnsmasq
  ansible.builtin.systemd_service:
    name: dnsmasq
    state: restarted
    enabled: true
  become: true